### ISSUE TITLE
Template uses outdated version of decky-frontend-lib

### ISSUE THREAD

**Issue by NGnius** [SteamDeckHomebrew/decky-plugin-template#2]
Currently decky-frontend-lib is set to v0.0.2, which is very out of date.

Recommendations:
- Set decky-frontend-lib version to `*` in package.json
- Delete package-lock.json (so that it doesn't use whatever version is in there)

**Comment by AAGaming00** [comment]
I think the issue here is that someone's locally linked setup slipped through into package-lock.json.

**Comment by TrainDoctor** [comment]
This is largely resolved. I'll replace this issue with a feature request to automatically update to the latest stable release of decky-frontend-lib.
