### ISSUE TITLE
Incorrect routing in template

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-plugin-template#35]
These lines should use Navigation instead
https://github.com/SteamDeckHomebrew/decky-plugin-template/blob/8f6c61207f4afe623d9f00b2cca3681434d9d4de/src/index.tsx#L70-L71

https://github.com/SteamDeckHomebrew/decky-plugin-template/blob/8f6c61207f4afe623d9f00b2cca3681434d9d4de/src/index.tsx#L85

**Comment by TrainDoctor** [comment]
Fixed in latest commit!
