### ISSUE TITLE
build scripts break with spaces in directory name

### ISSUE THREAD

**Issue by ArnoldSmith86** [SteamDeckHomebrew/decky-plugin-template#36]
Trying to get this running and doing it in directory `~/Projects/Steam Deck/decky-plugin-template` leads to errors because of lines like this:

https://github.com/SteamDeckHomebrew/decky-plugin-template/blob/8f6c61207f4afe623d9f00b2cca3681434d9d4de/.vscode/setup.sh#L43

I'll just rename the directory but I wanted to report it anyway.

**Comment by TrainDoctor** [comment]
While on *nix configurations (which the template is designed for) spaces in folder/filenames are not advisable, I've adjusted the template to hopefully resolve this. 498ca9b
