### ISSUE TITLE
Error: Failed to zip plugin.

### ISSUE THREAD

**Issue by watsonlu** [SteamDeckHomebrew/decky-plugin-template#38]
Hey guys,

When I run the build task with the same project I get the following error:

`created dist/index.js in 2.2s
INFO [decky::cli::plugin::build] Plugin does not require any remote binaries
INFO [decky::cli::plugin::build] Building py_modules
INFO [decky::cli::plugin::build] Zipping plugin
INFO [decky::cli::plugin::build] Zipping "pokedeck/LICENSE"
INFO [decky::cli::plugin::build] Zipping "pokedeck/main.py"
INFO [decky::cli::plugin::build] Zipping "pokedeck/package.json"
INFO [decky::cli::plugin::build] Zipping "pokedeck/plugin.json"
INFO [decky::cli::plugin::build] Zipping "pokedeck/README.md"
Error: Failed to zip plugin.

Caused by:
    0: IO error for operation on /tmp/decky/fj3Pq0TdoAtQ4pzM/dist: No such file or directory (os error 2)
    1: No such file or directory (os error 2)`

The /tmp/decky/fj3* file is created but everything seems to be owned by root:

`/tmp/decky/fj3Pq0TdoAtQ4pzM$ ls -la
total 16
drwxr-xr-x  4 root root 4096 Mar 27 14:01 .
drwxr-xr-x 11 root root 4096 Mar 27 14:07 ..
drwxr-xr-x  2 root root 4096 Mar 27 14:01 bin
drwxr-xr-x  2 root root 4096 Mar 27 14:01 py_modules`

**Comment by Enagan** [comment]
Running into the same issue here, not sure what do to about it!

**Comment by TrainDoctor** [comment]
No information on OS etc. I can't do much with this unless that sort of information is provided. Closing unless crucial information is provided.

**Comment by DarkZeros** [comment]
> Running into the same issue here, not sure what do to about it!

Did you manage to fix this? I am with the same problem.

**Comment by Enagan** [comment]
> > Running into the same issue here, not sure what do to about it!
> 
> Did you manage to fix this? I am with the same problem.

No, sorry. I never managed around it and gave up trying to get a plugin project going. Haven't retried since

**Comment by TrainDoctor** [comment]
> > > Running into the same issue here, not sure what do to about it!
> > 
> > 
> > Did you manage to fix this? I am with the same problem.
> 
> No, sorry. I never managed around it and gave up trying to get a plugin project going. Haven't retried since

We asked you for information on the OS, distro or anything but did not receive it so we could not help you.
