### ISSUE TITLE
Template - Automatically update version of decky-frontend-lib with new npm releases

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-plugin-template#4]
Could also be accomplished by using **latest version** in pnpm lock.

**Comment by TrainDoctor** [comment]
This will be accomplished via a *latest version* dependency to decky-frontend-lib.

**Comment by AAGaming00** [comment]
> This will be accomplished via a *latest version* dependency to decky-frontend-lib.

This is a bad idea. With how NPM handles versioning, the version defined in package.json will stay "latest", and so running npm i may automatically upgrade to a new major version of `decky-frontend-lib` with breaking changes. We should instead depend on the latest minor revision of a specific major version and manually update the template when a new major version releases.
