### ISSUE TITLE
Im getting logs that sre full of errors and my animation dont have a filename anymore.

### ISSUE THREAD

**Issue by Blueblackdragon** [SteamDeckHomebrew/decky-plugin-template#40]
Some of my animations are called ER9qn.webm previosly it always was the name that you downloaded from the store (Sometimes animation changer breaks for me so i delete it. Once i could keep the animation not anymore know i have to copy them over and there filename is random). Within desktop mode if you go to .steam > root > logs I have logs that have constant errors and they disappear if I delete animation changer.

**Comment by TrainDoctor** [comment]
I'm not sure why this was filed on the plugin template.
