### ISSUE TITLE
Why no barebones example?

### ISSUE THREAD

**Issue by Merith-TK** [SteamDeckHomebrew/decky-plugin-template#5]
I personally really dislike when an example has more features and functions, than is necessary to demonstrate how to use it.

Why not have multiple branches, one for the NodeJS/NPM/Yarn template, and another for the barebones, and then let the user decide which one to use? It seems bulky and annoying to someone who does not like JS based languages, (which is an surprising amount of people)

Can we get an "bare bones" template at the very least, where it is just the basics on how to register an DeckyLoader plugin? rather than have an complicated UI library?

-- edit

The repo states this is an example of the React Based UI Library, while the name is Plugin Template, which suggests this is an template repo of the absolute *bare bones* to run something (IE: an hello world)

**Comment by TrainDoctor** [comment]
We do not intend to make a ton of templates for other implementations. This is up to other developers. We are an entirely volunteer group. We intend to provide support for plugin developers if they use this plugin template and decky-frontend-lib. This **is** a barebones example and if other users want to contribute their templates they've developed they can do so.

In terms of not liking JS/Web languages, most of the team doesn't either but the Steam UI is react based and as such usage of react is the best way to integrate with the Steam Deck UI.

Once the react update is finished and we publish a full release we'll be moving to supporting other backends but our only supported frontend will be react and this is unlikely to ever change. Your are free to contribute your own templates extensions to decky-loader but this should communicate our focus which is bringing the best plugin experience to Steam Deck users we can and providing support to developers. This cannot entail coming up with entire new implementations for frameworks that would take time away from our focus on getting fundamental infrastructure for our next release up and running.

Thanks for your feedback and apologies we can't work on your desired version.

**Comment by Merith-TK** [comment]
Its not other backends that I was hoping for, 

just an barebones plugin template without all of the UI stuff you guys use, literally just enough for an button to be registered on the Plugin Menu, so people who dont want to use decky-frontend-lib can use something

(If I am being mistaken in how this works such as if DFL is required for the plugin button registry let me know)

**Comment by vrman123** [comment]
just thought it might be worth adding (very late, i'm aware sorry for necropost etc etc) that there *is* a barebones plugin https://github.com/SteamDeckHomebrew/decky-playground and it existed before this issue was opened
